"""
Core Pydantic Schemas for S-AI-BER.

This module defines the standardized data structures used for communication
between different layers of the application (e.g., API, Orchestrator, Agents).
Using these schemas ensures data consistency and validation.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class UserQueryRequest(BaseModel):
    """Schema for an incoming user query from the API."""
    prompt: str = Field(..., description="The natural language query from the user.")
    session_id: Optional[str] = Field(None, description="An optional ID to maintain conversation history.")

class Task(BaseModel):
    """
    Schema representing a single, specific task for an agent.
    This is the structure the LLM is expected to generate.
    """
    task_id: int = Field(..., description="A unique identifier for the task within a plan.")
    agent: str = Field(..., description="The name of the agent to execute this task.")
    action: str = Field(..., description="The specific action the agent should perform.")
    target: str = Field(..., description="The target of the action (e.g., IP address, domain).")
    params: Dict[str, Any] = Field({}, description="Additional parameters for the agent's action.")
    dependencies: List[int] = Field([], description="List of task_ids that must be completed before this task can start.")

class ExecutionPlan(BaseModel):
    """A list of tasks that represents the full plan generated by the LLM."""
    tasks: List[Task]

class AvengerResult(BaseModel):
    """Standardized schema for the output of any agent task."""
    task_id: int
    status: str = Field(..., description="The status of the task execution ('success', 'failure').")
    output: Any = Field(..., description="The structured output from the agent's tool (e.g., JSON from Nmap).")
    error_message: Optional[str] = Field(None, description="An error message if the task failed.")

class FinalReport(BaseModel):
    """The final report presented to the user."""
    summary: str = Field(..., description="A natural language summary of the findings.")
    results: List[AvengerResult] = Field(..., description="A detailed list of results from each agent task.")
    session_id: str
